#:schema node_modules/wrangler/config-schema.json
name = "gamezilla"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
name = "DB"
AUTH_SECRET = "n5iqHEUc0BfH2IceFBFnrWj3fyrGlTaeQM+yvDoADWE="

[[d1_databases]]
migrations_dir = "./src/db/migrations"
binding = "DB"
database_name = "gamezilla"
database_id = "2c2dda3e-7bee-43e0-820e-c9172d5e62b5"